### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "getpagesize" referenced by "libturbo-dex.so"...

### ISSUE THREAD

**Issue by ijustyce** [asLody/TurboDex#4]
按照readme，我在gradle  里添加     compile 'com.github.asLody:turbodex:1.0.0'  然后在Application类里添加： TurboDex.enableTurboDex();
运行后，出现如标题所示错误！

**Comment by qfzc** [comment]
同样出现该问题

**Comment by qiujuer** [comment]
手机是什么型号？系统版本是多少? @ijustyce

**Comment by qfzc** [comment]
@qiujuer  我的手机是nexus5

**Comment by asLody** [comment]
原因是so没有成功被打包进apk，手动把so放到项目的src/main/jniLibs就可以了

**Comment by qiujuer** [comment]
@ijustyce 请稍等，是因为库关联的问题，正在修改并重新发布。

**Comment by qiujuer** [comment]
1.1.0 版本已经修复该问题。
